### ISSUE TITLE
Upgrade IBC-Go to v0.3.1

### ISSUE THREAD

**Issue by TxCorpi0x** [ComposableFi/ibc-go#17]
## Summary
Make the repo in sync with the original lib, Upgrade and merge the code.

## Problem Definition
The new version of upstream [lib](https://github.com/cosmos/ibc-go/releases/tag/v3.1.0) is released.

## Proposal
This repo should be upgraded to the latest version code-base.

**Comment by seunlanlege** [comment]
see PR comments
